# config/llava_config.yaml
model:
  name: "llava-1.5"
  model_path: "path/to/llava/weights"
  tokenizer_path: "path/to/tokenizer"
  max_length: 2048
  default_params:
    temperature: 0.7
    top_p: 0.9
  device: "cuda"
